// room context
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_ROOM_CODE = 'UPDATE_ROOM_CODE';
export const UPDATE_ROOM_LANGUAGE = 'UPDATE_ROOM_LANGUAGE';
export const UPDATE_ROOM_INPUT = 'UPDATE_ROOM_INPUT';
export const UPDATE_ROOM_OUTPUT = 'UPDATE_ROOM_OUTPUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_ROOM_MESSAGES = 'UPDATE_ROOM_ MESSAGES';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const UPDATE_ROOM_USERS = 'UPDATE_ROOM_USERS';
export const SET_LOADING = 'SET_LOADING';

export const CREATE_FILE = 'CREATE_FILE';
export const UPDATE_FILE_LIST = 'UPDATE_FILE_LIST';


